"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var router = express_1.default.Router();
from;
'../controllers';
var indexController = require("../controllers/index");
router.get('/', indexController.displayHomePage);
router.get('/home', indexController.displayHomePage);
router.get('/aboutme', indexController.displayAboutMePage);
router.get('/projects', indexController.displayProjectsPage);
router.get('/services', indexController.displayServicesPage);
router.get('/contactme', indexController.displayContactMePage);
exports.default = router;
